### PR TITLE
Cleaning submodules and rename engineering package

### LINKED ISSUE #10: Rename `engineering` package naming to `registry`
@tloubrieu-jpl commented on [Wed Jul 07 2021](https://github.com/NASA-PDS/registry-api-service/issues/50)

## Motivation
...so that I can feel included/welcomed in part of the development contributions. 
## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## Engineering Details

---

@jordanpadams commented on [Tue Oct 19 2021](https://github.com/NASA-PDS/registry-api-service/issues/50#issuecomment-946823212)

@tloubrieu-jpl adding this towards the top of the list before we get too far into development and someone tries to extend the service

### PR DESCRIPTION
**Pull request by tloubrieu-jpl**
## 🗒️ Summary

fixes #10 

and clean the pom for better integration in multimodule project

### CODE REVIEW

**Comment by al-niessner** [comment]
I made similar changes on #20 so given the conflicts you may want to simply abandon this change.

**Comment by jordanpadams** [comment]
@al-niessner we probably just need to try this again but with the latest codebase

**Comment by al-niessner** [comment]
Actually, I similarly had to rename all the sub modules and fix up the POMs to make it all self consistent that I am strong suggesting that keeping this is not all that useful and was giving you a graceful out with the conflicts.

**Comment by jordanpadams** [comment]
per tag-up closing this PR. will re-do

**Pull request closed without merging**
