### PR TITLE
increase java process memory allocation to 75% of available RAM...

### LINKED ISSUE #296: API crashes with JVM memory error on data sets with very large labels (>1MB)
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did a query for products of the SHERLOC bundle, I noticed having performing the query a few times, the API stopped working. After further investigation, it appears the API crashed, with initial thoughts being due to a JVM memory overflow error

### 🕵️ Expected behavior

I expected the query would return as expected.

### 📜 To Reproduce

1. performed the following query a few times:

```
curl --GET "https://pds.nasa.gov/api/search/1/products?q=lidvid%20like%20%22urn:nasa:pds:mars2020_sherloc*%22"
```
2. eventually started seeing 500 errors from all endpoints.
3. from the server logs, the following error was noted:
```
2023-03-22 19:01:32.751 DEBUG 1 --- [-nio-80-exec-10] org.opensearch.client.RestClient         : request [POST [https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com:443/registry,psa-prod:registry,naif-prod-ccs:registry,rms-prod:registry,sbnumd-prod-ccs:registry,geo-prod-ccs:registry,atm-prod-ccs:registry,sbnpsi-prod-ccs:registry,ppi-prod-ccs:registry,img-prod-ccs:registry/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true](https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com/registry,psa-prod:registry,naif-prod-ccs:registry,rms-prod:registry,sbnumd-prod-ccs:registry,geo-prod-ccs:registry,atm-prod-ccs:registry,sbnpsi-prod-ccs:registry,ppi-prod-ccs:registry,img-prod-ccs:registry/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true)] failed
```

### 🖥 Environment Info

_No response_

### 📚 Version of Software Used

_No response_

### 🩺 Test Data / Additional context

* The bundle in question is here: https://pds-geosciences.wustl.edu/m2020/urn-nasa-pds-mars2020_sherloc/ 
* The specific collection I am finding some large labels: https://pds-geosciences.wustl.edu/m2020/urn-nasa-pds-mars2020_sherloc/data_raw/
* and example of a very large label: https://pds-geosciences.wustl.edu/m2020/urn-nasa-pds-mars2020_sherloc/data_raw/sol_00004/SS__0004_0667298185_056ECA__0010052SRLC10002_0_____J10.xml 

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### LINKED ISSUE #300: Update Java params and Docker image to expand JVM memory beyond 50%
## 💡 Description

Default Java 11 JVM config is to use 50% of available memory. Since registry-api is running on it's own ECS cluster, we want to run this with more available memory (75%?)

### PR DESCRIPTION
**Pull request by alexdunnjpl**
…hardcoded)

## 🗒️ Summary
Per title

## ⚙️ Test Data and/or Report
@jimmie @jordanpadams I'm unsure how to test this - running the Dockerfile as-is resulted in `Error: Invalid or corrupt jarfile /usr/local/registry-api-service/registry-api-service.jar`, which remains true after the change.

## ♻️ Related Issues
fixes #296 
fixes #300

### CODE REVIEW

**Comment by jimmie** [comment]
A (the) docker build argument (api_jar) to is the location of the service jar file (the current release would be https://github.com/NASA-PDS/registry-api/releases/download/v1.1.12/registry-api-service-1.1.12.jar.) Typically if this is not specified or an invalid location is given (maybe there's a way to verify the validity?) - the message you saw is generated.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl ☝️

**Comment by alexdunnjpl** [comment]
I can confirm that adding the argument in question does not break the API.

**Review by tloubrieu-jpl — APPROVED** [review]
Perfect, thanks @alexdunnjpl

**Comment by alexdunnjpl** [comment]
Merged conflict, retaining initial heap size of 512Mb and overwriting 2Gb max with new 6Gb max

**Pull request merged**
