### PR TITLE
issue 10: change engineering to registry

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Full rename, build docker images, and run test using latest harvest. 

## ⚙️ Test Data and/or Report
Returned this data:
```
$ curl --location --request GET 'http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:data_eetable::1.0' --header 'Accept: application/vnd.nasa.pds.pds4+xml' | xmllint -format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7551    0  7551    0     0   167k      0 --:--:-- --:--:-- --:--:--  167k
<?xml version="1.0"?>
<pds_api:products xmlns:pds_api="http://pds.nasa.gov/api" xmlns:ops="https://pds.nasa.gov/pds4/ops/v1">
  <pds_api:Summary>
    <pds_api:q/>
    <pds_api:hits>1</pds_api:hits>
    <pds_api:took>11</pds_api:took>
    <pds_api:start>0</pds_api:start>
    <pds_api:limit>10</pds_api:limit>
    <pds_api:sort/>
    <pds_api:properties>
      <pds_api:properties>ops:Data_File_Info/ops:creation_date_time</pds_api:properties>
      <pds_api:properties>ops:Data_File_Info/ops:file_name</pds_api:properties>
      <pds_api:properties>ops:Data_File_Info/ops:file_ref</pds_api:properties>
      <pds_api:properties>ops:Data_File_Info/ops:file_size</pds_api:properties>
      <pds_api:properties>ops:Data_File_Info/ops:md5_checksum</pds_api:properties>
      <pds_api:properties>ops:Data_File_Info/ops:mime_type</pds_api:properties>
      <pds_api:properties>ops:Harvest_Info/ops:node_name</pds_api:properties>
      <pds_api:properties>ops:Label_File_Info/ops:blob</pds_api:properties>
      <pds_api:properties>ops:Label_File_Info/ops:creation_date_time</pds_api:properties>
      <pds_api:properties>ops:Label_File_Info/ops:file_name</pds_api:properties>
      <pds_api:properties>ops:Label_File_Info/ops:file_ref</pds_api:properties>
      <pds_api:properties>ops:Label_File_Info/ops:file_size</pds_api:properties>
      <pds_api:properties>ops:Label_File_Info/ops:md5_checksum</pds_api:properties>
    </pds_api:properties>
  </pds_api:Summary>
  <pds_api:data>
    <pds_api:product>
      <pds_api:id>urn:nasa:pds:izenberg_pdart14_meap:data_eetable::1.0</pds_api:id>
      <pds_api:meta>
        <node_name>PSA</node_name>
        <ops:Label_File_Info>
          <ops:file_name>collection_eetable_inventory.xml</ops:file_name>
          <ops:file_ref>/var/local/harvest/archive/data_eetable/collection_eetable_inventory.xml</ops:file_ref>
          <ops:creation_date>2022-03-07T20:53:17Z</ops:creation_date>
          <ops:file_size>5480</ops:file_size>
          <ops:md5_checksum>e2eb335391dfc4d838c632667a921eaa</ops:md5_checksum>
        </ops:Label_File_Info>
        <ops:Data_Files>
          <ops:Data_Files>
            <ops:file_name>collection_eetable_inventory.csv</ops:file_name>
            <ops:file_ref>/var/local/harvest/archive/data_eetable/collection_eetable_inventory.csv</ops:file_ref>
            <ops:creation_date>2022-03-07T20:53:17Z</ops:creation_date>
            <ops:file_size>253</ops:file_size>
            <ops:md5_checksum>216b3f5445414376ccdacf71ed9457f1</ops:md5_checksum>
            <ops:mime_type>text/plain</ops:mime_type>
          </ops:Data_Files>
        </ops:Data_Files>
      </pds_api:meta>
      <pds_api:pds4>
        <Product_Collection xmlns="http://pds.nasa.gov/pds4/pds/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1E00.xsd">
          <Identification_Area>
            <logical_identifier>urn:nasa:pds:izenberg_pdart14_meap:data_eetable</logical_identifier>
            <version_id>1.0</version_id>
            <title>Izenberg PDART 2014 MESSENGER Advanced Products Energetic Electrons Table Collection</title>
            <information_model_version>1.14.0.0</information_model_version>
            <product_class>Product_Collection</product_class>
            <Citation_Information>
              <author_list>Izenberg, N.</author_list>
              <publication_year>2016</publication_year>
              <keyword>MESSENGER</keyword>
              <keyword>Neutron Spectrometer</keyword>
              <description>Izenberg PDART 2014 MESSENGER Advanced Products Energetic Electrons Table Collection</description>
            </Citation_Information>
            <Modification_History>
              <Modification_Detail>
                <modification_date>2016-04-08</modification_date>
                <version_id>1.0</version_id>
                <description>Initial PDS4 version</description>
              </Modification_Detail>
            </Modification_History>
          </Identification_Area>
          <Context_Area>
            <Time_Coordinates>
              <start_date_time>2011-03-25Z</start_date_time>
              <stop_date_time>2015-04-30Z</stop_date_time>
            </Time_Coordinates>
            <Primary_Result_Summary>
              <purpose>Science</purpose>
              <processing_level>Derived</processing_level>
            </Primary_Result_Summary>
            <Investigation_Area>
              <name>MESSENGER</name>
              <type>Mission</type>
              <Internal_Reference>
                <lid_reference>urn:nasa:pds:context:investigation:mission.messenger</lid_reference>
                <reference_type>collection_to_investigation</reference_type>
              </Internal_Reference>
            </Investigation_Area>
            <Observing_System>
              <name>MESSENGER</name>
              <Observing_System_Component>
                <name>MESSENGER</name>
                <type>Host</type>
                <Internal_Reference>
                  <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.mess</lid_reference>
                  <reference_type>is_instrument_host</reference_type>
                </Internal_Reference>
              </Observing_System_Component>
              <Observing_System_Component>
                <name>NS</name>
                <type>Instrument</type>
                <Internal_Reference>
                  <lid_reference>urn:nasa:pds:context:instrument:ns.mess</lid_reference>
                  <reference_type>is_instrument</reference_type>
                </Internal_Reference>
              </Observing_System_Component>
            </Observing_System>
            <Target_Identification>
              <name>Mercury</name>
              <type>Planet</type>
              <Internal_Reference>
                <lid_reference>urn:nasa:pds:context:target:planet.mercury</lid_reference>
                <reference_type>collection_to_target</reference_type>
              </Internal_Reference>
            </Target_Identification>
          </Context_Area>
          <Collection>
            <collection_type>Data</collection_type>
          </Collection>
          <File_Area_Inventory>
            <File>
              <file_name>collection_eetable_inventory.csv</file_name>
              <creation_date_time>2016-04-08</creation_date_time>
            </File>
            <Inventory>
              <offset unit="byte">0</offset>
              <parsing_standard_id>PDS DSV 1</parsing_standard_id>
              <records>3</records>
              <record_delimiter>Carriage-Return Line-Feed</record_delimiter>
              <field_delimiter>Comma</field_delimiter>
              <Record_Delimited>
                <fields>2</fields>
                <groups>0</groups>
                <Field_Delimited>
                  <name>Member Status</name>
                  <field_number>1</field_number>
                  <data_type>ASCII_String</data_type>
                  <maximum_field_length unit="byte">1</maximum_field_length>
                  <description>
                        P indicates primary member of the collection
                        S indicates secondary member of the collection
                    </description>
                </Field_Delimited>
                <Field_Delimited>
                  <name>LIDVID_LID</name>
                  <field_number>2</field_number>
                  <data_type>ASCII_LIDVID_LID</data_type>
                  <maximum_field_length unit="byte">255</maximum_field_length>
                  <description>
                        The LID or LIDVID of a product that is a member
                        of the collection.
                    </description>
                </Field_Delimited>
              </Record_Delimited>
              <reference_type>inventory_has_member_product</reference_type>
            </Inventory>
          </File_Area_Inventory>
        </Product_Collection>
      </pds_api:pds4>
    </pds_api:product>
  </pds_api:data>
</pds_api:products>
```

## ♻️ Related Issues
issue #10 
closed PR #97 (redo)

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl @tdddblog 

Problems with #99 merge. I updated to what I believe is latest harvest data today using NASA-PDS/pds-registry-app and create-registry, harvest, and then load-data in clean (empty) elastic search.

To test, did this:
```
$ curl --location --request GET 'http://localhost:8080/products'
{"summary":{"hits":0,"took":16,"start":0,"limit":100,"sort":[],"properties":[]},"data":[]}
```

The relavent part of the log shows that __"ops:Tracking_Meta/ops:archive_status":["archived","certified"],__ #99 has been merged. 
```
2022-03-07 23:10:59.307 DEBUG 55 --- [nio-8080-exec-3] g.n.p.a.r.c.MyProductsApiBareController  : baseUrl is http://localhost:8080/
2022-03-07 23:10:59.314  INFO 55 --- [nio-8080-exec-3] g.n.p.a.r.e.b.RequestAndResponseContext  : Matched output type as '*/*' from '*/*'.
2022-03-07 23:10:59.314 DEBUG 55 --- [nio-8080-exec-3] g.n.p.a.r.e.b.ProductQueryBuilderUtil    : addArchiveStatusFilter: [archived, certified]
2022-03-07 23:10:59.315 DEBUG 55 --- [nio-8080-exec-3] lasticSearchRegistrySearchRequestBuilder : Elasticsearch request :SearchRequest{searchType=QUERY_THEN_FETCH, indices=[registry], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=null, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"from":0,"size":100,"timeout":"60s","query":{"bool":{"must":[{"terms":{"ops:Tracking_Meta/ops:archive_status":["archived","certified"],"boost":1.0}},{"bool":{"adjust_pure_negative":true,"minimum_should_match":"1","boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":[],"excludes":["ops:Label_File_Info/ops:blob","ops:Label_File_Info/ops:json_blob"]}}}
```

However, if I look at my elasticsearch database and search for "ops:Tracking_Meta/ops:archive_status", I find that all of them are: `"ops:Tracking_Meta/ops:archive_status":"staged"`.

Is the correct fix to update the application properties to include staged? Is there a newer harvest and I need to get from somewhere other than NASA-PDS/pds-registry-app? How did testing pass if neither of these?

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Ready-ish for review. I changed the applications properties and it works. If that is not the right fix, then wait on the review.

If you notice the summary on the singular (not supposed to be there) that is from lack of regression checks on #99 and will require fixing again. Either keep it until after opensearch or I will fix it again in opensearch if the refactoring gets me into that area.

**Comment by al-niessner** [comment]
Also see node_name is wrong -- should be '<ops:Harvest_Info><ops:node_name>' but I think PR #9 was a merge while I was still making changes to the work. It should be appended or included with the #101 and #102 work because they are changing the files.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Forgot lexer. One moment.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Ready-ish for review again given all previous remarks but at least all of the code has changed this time. 'find -type f -exec grep engineering {} \; -print' only finds references in .git directory.

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
> @jordanpadams @tloubrieu-jpl
> 
> Ready-ish for review. I changed the applications properties and it works. If that is not the right fix, then wait on the review.
> 
> If you notice the summary on the singular (not supposed to be there) that is from lack of regression checks on #99 and will require fixing again. Either keep it until after opensearch or I will fix it again in opensearch if the refactoring gets me into that area.

@al-niessner the application.properties was actually right. The default is "staged" upon ingestion with the intent that users will be ingesting large chunks of data prior to public release and then "flip a switch" to change it to archived or certified. So for your testing, you will want to change that archive status. That should be in the harvest docs somewhere.

Additionally, I believe there is a setting in harvest to tell it to set the status to "archived" by default, instead of staged.

**Comment by jordanpadams** [comment]
@al-niessner I think you will also need to create a new PR from your branch. This PR is already merged and closed.

**Pull request merged**
