### PR TITLE
Branch workflows now include not just unit tests but integration tests using Docker Compositions

### LINKED ISSUE #269: Add registry/docker compose integration tests to github action on dev branches
## 💡 Description

See github action https://github.com/NASA-PDS/registry-api/blob/main/.github/workflows/branch-cicd.yaml
And automated integration tests with profile int-registry-batch-loader on  https://github.com/NASA-PDS/registry/tree/main/docker

### PR DESCRIPTION
**Pull request by nutjob4life**
## 🗒️ Summary

Merge this to resolve #269 which adds a full integration test to the branch-triggered workflow.

## ⚙️ Test Data and/or Report

You can see a run of this [in the sandbox](https://github.com/nasa-pds-engineering-node/registry-api/actions/runs/5811878215/job/15756081690). Yes, the run is "in the red", but that's because integration tests currently have 34 failed assertions. Successful exposition!

## ♻️ Related Issues

- #269

### CODE REVIEW

**Review by alexdunnjpl — APPROVED** [review]
LGTM!

Now we just have to get around to resolving those failing tests 🥲

**Comment by alexdunnjpl** [comment]
@nutjob4life actually, real-talk, would it be viable to have that as a separate stage?  If only so that unit-test regressions don't get ignored because "BIT/BT always fails now".

**Comment by nutjob4life** [comment]
> LGTM!
> 
> Now we just have to get around to resolving those failing tests 🥲

Sooo faaast @alexdunnjpl! 🏎▁▂▃▄▅▆▆▇▇██💨

**Comment by nutjob4life** [comment]
> @nutjob4life actually, real-talk, would it be viable to have that as a separate stage? If only so that unit-test regressions don't get ignored because "BIT/BT always fails now".

[Absolutely](https://github.com/NASA-PDS/registry-api/issues/new?assignees=jordanpadams&labels=needs%3Atriage%2Crequirement&projects=&template=feature_request.yml&title=As+a+%3Cwhat+is+the+user%27s+role%3F%3E%2C+I+want+to+%3Cwhat+is+the+user+trying+to+accomplish%3F%3E), @alexdunnjpl

**Comment by alexdunnjpl** [comment]
Just saw that comment/link after missing it the first time.

@jordanpadams your thoughts on the above?  Should I open a ticket for it?

**Comment by jordanpadams** [comment]
@alexdunnjpl See #397 comments

**Pull request merged**
