### PR TITLE
issue #93: add pds_api namespace

### LINKED ISSUE #93: Content type pds4+xml does not namespace tags in <pds_api:meta> with pds_api
## 🐛 Describe the bug

The desire is to have pds_api namespace prefix all of the tags within meta instead of how it is:

```
  <pds_api:meta>
    <node_name>PSA</pds_api:node_name>
    <label_file>
      <file_name>ns_inst.xml</pds_api:file_name>
      <file_ref>/var/local/harvest/archive/document/ns_inst.xml</pds_api:file_ref>
      <creation_date>2022-01-24T20:08:23Z</pds_api:creation_date>
      <file_size>3589</pds_api:file_size>
      <md5_checksum>a8d09cca0a01728db50c15052c2736cf</pds_api:md5_checksum>
    </label_file>
    <data_files>
      <data_files>
        <file_name>ns_inst.pdf</pds_api:file_name>
        <file_ref>/var/local/harvest/archive/document/ns_inst.pdf</pds_api:file_ref>
        <creation_date>2022-01-24T20:08:23Z</pds_api:creation_date>
        <file_size>138172</pds_api:file_size>
        <md5_checksum>8103f20c13a3c321dac4a193aba19d16</pds_api:md5_checksum>
        <mime_type>application/pdf</pds_api:mime_type>
      </data_files>
    </data_files>
  </pds_api:meta>
```

## 📜 To Reproduce
`$ curl --location --request GET 'http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0' --header 'Accept: application/pds4+xml' | xmllint --format -`

## 🕵️ Expected behavior

```
  <pds_api:meta>
    <pds_api:node_name>PSA</pds_api:node_name>
    <pds_api:label_file>
      <pds_api:file_name>ns_inst.xml</pds_api:file_name>
      <pds_api:file_ref>/var/local/harvest/archive/document/ns_inst.xml</pds_api:file_ref>
      <pds_api:creation_date>2022-01-24T20:08:23Z</pds_api:creation_date>
      <pds_api:file_size>3589</pds_api:file_size>
      <pds_api:md5_checksum>a8d09cca0a01728db50c15052c2736cf</pds_api:md5_checksum>
    </pds_api:label_file>
    <pds_api:data_files>
      <pds_api:data_files>
        <pds_api:file_name>ns_inst.pdf</pds_api:file_name>
        <pds_api:file_ref>/var/local/harvest/archive/document/ns_inst.pdf</pds_api:file_ref>
        <pds_api:creation_date>2022-01-24T20:08:23Z</pds_api:creation_date>
        <pds_api:file_size>138172</pds_api:file_size>
        <pds_api:md5_checksum>8103f20c13a3c321dac4a193aba19d16</pds_api:md5_checksum>
        <pds_api:mime_type>application/pdf</pds_api:mime_type>
      </pds_api:data_files>
    </pds_api:data_files>
  </pds_api:meta>
```

---

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Cannot update the beans generated by swagger easily so overrode the XmlMapper writer creation to add it instead. Required wrapping up XMLStreamWriter so force namespace usage.

## ⚙️ Test Data and/or Report
```
$ curl --location --request GET 'http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0' --header 'Accept: application/pds4+xml' | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4427    0  4427    0     0  13496      0 --:--:-- --:--:-- --:--:-- 13496
<?xml version="1.0"?>
<pds_api:product xmlns:pds_api="http://pds.nasa.gov/api">
  <pds_api:id>urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0</pds_api:id>
  <pds_api:meta>
    <pds_api:node_name>PSA</pds_api:node_name>
    <pds_api:label_file>
      <pds_api:file_name>ns_inst.xml</pds_api:file_name>
      <pds_api:file_ref>/var/local/harvest/archive/document/ns_inst.xml</pds_api:file_ref>
      <pds_api:creation_date>2022-01-24T20:08:23Z</pds_api:creation_date>
      <pds_api:file_size>3589</pds_api:file_size>
      <pds_api:md5_checksum>a8d09cca0a01728db50c15052c2736cf</pds_api:md5_checksum>
    </pds_api:label_file>
    <pds_api:data_files>
      <pds_api:data_files>
        <pds_api:file_name>ns_inst.pdf</pds_api:file_name>
        <pds_api:file_ref>/var/local/harvest/archive/document/ns_inst.pdf</pds_api:file_ref>
        <pds_api:creation_date>2022-01-24T20:08:23Z</pds_api:creation_date>
        <pds_api:file_size>138172</pds_api:file_size>
        <pds_api:md5_checksum>8103f20c13a3c321dac4a193aba19d16</pds_api:md5_checksum>
        <pds_api:mime_type>application/pdf</pds_api:mime_type>
      </pds_api:data_files>
    </pds_api:data_files>
  </pds_api:meta>
  <pds_api:pds4>
    <Product_Document xmlns="http://pds.nasa.gov/pds4/pds/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1E00.xsd">
      <Identification_Area>
        <logical_identifier>urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst</logical_identifier>
        <version_id>1.0</version_id>
        <title>MESSENGER Neutron Spectrometer (NS) Description</title>
        <information_model_version>1.14.0.0</information_model_version>
        <product_class>Product_Document</product_class>
        <Citation_Information>
          <publication_year>2016</publication_year>
          <description>Description of the MESSENGER Neutron Spectrometer (NS).</description>
        </Citation_Information>
        <Modification_History>
          <Modification_Detail>
            <modification_date>2016-03-16</modification_date>
            <version_id>1.0</version_id>
            <description>Initial PDS4 version.</description>
          </Modification_Detail>
        </Modification_History>
      </Identification_Area>
      <Context_Area>
        <Investigation_Area>
          <name>MESSENGER</name>
          <type>Mission</type>
          <Internal_Reference>
            <lid_reference>urn:nasa:pds:context:investigation:mission.messenger</lid_reference>
            <reference_type>document_to_investigation</reference_type>
          </Internal_Reference>
        </Investigation_Area>
        <Observing_System>
          <name>MESSENGER</name>
          <Observing_System_Component>
            <name>MESSENGER</name>
            <type>Host</type>
            <Internal_Reference>
              <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.mess</lid_reference>
              <reference_type>is_instrument_host</reference_type>
            </Internal_Reference>
          </Observing_System_Component>
          <Observing_System_Component>
            <name>NS</name>
            <type>Instrument</type>
            <Internal_Reference>
              <lid_reference>urn:nasa:pds:context:instrument:ns.mess</lid_reference>
              <reference_type>is_instrument</reference_type>
            </Internal_Reference>
          </Observing_System_Component>
        </Observing_System>
        <Target_Identification>
          <name>Mercury</name>
          <type>Planet</type>
          <Internal_Reference>
            <lid_reference>urn:nasa:pds:context:target:planet.mercury</lid_reference>
            <reference_type>document_to_target</reference_type>
          </Internal_Reference>
        </Target_Identification>
      </Context_Area>
      <Document>
        <publication_date>2016-03-16</publication_date>
        <description>Description of the MESSENGER Neutron Spectrometer (NS).</description>
        <Document_Edition>
          <edition_name>MESSENGER NS Instrument Description</edition_name>
          <language>English</language>
          <files>1</files>
          <Document_File>
            <file_name>ns_inst.pdf</file_name>
            <document_standard_id>PDF/A</document_standard_id>
          </Document_File>
        </Document_Edition>
      </Document>
    </Product_Document>
  </pds_api:pds4>
</pds_api:product>
```
## ♻️ Related Issues

Resolves #93

### CODE REVIEW

**Comment by al-niessner** [comment]
@tloubrieu-jpl need a review. I cannot merge without it.

**Review by tloubrieu-jpl — CHANGES_REQUESTED** [review]
Thanks @al-niessner ,

I am having an error when I launch the service with `mvn spring-boot:run`

The error is:
[INFO] Attaching agents: []
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 

        at gov.nasa.pds.api.engineering.SpringBootMain.main(SpringBootMain.java:26)

I don't see what can cause that. I retried with the main branch and was able to launch and build. Any ideas what the issue is ?

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

main branch builds and runs for me as well. When I realized I was on main, switched to issue_93 branch and it builds:

```
INFO] Reactor Summary:
[INFO] 
[INFO] gov.nasa.pds:registry-api-model 0.5.0-SNAPSHOT ..... SUCCESS [02:03 min]
[INFO] PDS API Search Query Lexer 1.1.0-SNAPSHOT .......... SUCCESS [ 25.859 s]
[INFO] gov.nasa.pds.api.registry-service 0.5.0-SNAPSHOT ... SUCCESS [01:01 min]
[INFO] gov.nasa.pds:registry 0.5.0-SNAPSHOT ............... SUCCESS [  0.267 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

I get some warnings at runtime that I think have always been there:

```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for gov.nasa.pds:registry-api-service:jar:0.5.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ line 50, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

It is up and running in the sense that this curl works:

```
$ curl --location --request GET 'http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0' --header 'Accept: application/pds4+xml' | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4427    0  4427    0     0  11322      0 --:--:-- --:--:-- --:--:-- 11293
<?xml version="1.0"?>
<pds_api:product xmlns:pds_api="http://pds.nasa.gov/api">
  <pds_api:id>urn:nasa:pds:izenberg_pdart14_meap:document:ns_inst::1.0</pds_api:id>
```

I am building and running from docker using these two commands:

```
ver=wip ; docker build --build-arg version=${ver} --file service/docker/Dockerfile.local --tag registry:${ver} . && docker_scrub.sh

ver=wip ; docker run --name registry --network pds  --publish 8080:8080 --rm --volume /home/niessner/Projects/PDS/registry-api/service/src/main/resources/application.properties.docker:/usr/local/registry-${ver}/service/target/classes/application.properties    registry:${ver}
```

I get strange errors, although not sure it is the one you are seeing, when I forget to start elasticsearch.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

I've been able to run the request /products/<lidvid> and I can see your update but the request /products fails with error 500, for any Accept value I believe, for example:

curl --location --request GET 'http://localhost:8080/products'


in logs:

2022-02-17 12:49:39.603 ERROR 30059 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.Error: Unresolved compilation problem: 
] with root cause

java.lang.Error: Unresolved compilation problem: 

        at gov.nasa.pds.api.engineering.elasticsearch.business.ProductQueryBuilderUtil.createPqlQuery(ProductQueryBuilderUtil.java:36) ~[classes/:na]
        at gov.nasa.pds.api.engineering.elasticsearch.ElasticSearchRegistrySearchRequestBuilder.getSearchProductsRequest(ElasticSearchRegistrySearchRequestBuilder.java:103) ~[classes/:na]
        at gov.nasa.pds.api.engineering.controllers.MyProductsApiBareController.getProducts(MyProductsApiBareController.java:78) ~[classes/:na]
        at gov.nasa.pds.api.engineering.controllers.MyProductsApiBareController.getProductsResponseEntity(MyProductsApiBareController.java:95) ~[classes/:na]
        at gov.nasa.pds.api.engineering.controllers.MyProductsApiController.products(MyProductsApiController.java:55) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

I am still at a loss. I get this from the curl and log has no errors:

```
$ curl --location --request GET 'http://localhost:8080/products'
{"summary":{"hits":17,"took":194,"start":0,"limit":100,"sort":[],"properties":["_package_id","cart:Bounding_Coordinates.cart:east_bounding_coordinate","cart:Bounding_Coordinates.cart:north_bounding_coordinate","cart:Bounding_Coordinates.cart:south_bounding_coordinate",  ...snip... "pds:Document_Edition.pds:language":["English"],"pds:Investigation_Area.pds:type":["Mission"]}}]}
```

```
$ git status
On branch issue_93
Your branch is up to date with 'origin/issue_93'.
```

**Comment by tloubrieu-jpl** [comment]
@al-niessner I don't understand what happened. I was able to reproduce that error again today and then I checked out the main branch to check that it worked (it did) and checked out issue_93 again and build it again and now it works !

I am keeping it that way, thanks

**Review by tloubrieu-jpl — APPROVED** [review]

**Pull request merged**
